name: Sync Deploy

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync:
    uses: qntx/workflows/.github/workflows/sync-repo-folder.yml@main
    with:
      source_repo: "qntx/facilitator"
      source_folder: "deploy"
      commit_message: "chore: sync deploy from source repo"
